### ISSUE TITLE
Running for altcoin

### ISSUE THREAD

**Issue by cymich** [moneroexamples/onion-bitcoin-blockchain-explorer#1]
Hello,

We would like to use your explorer for an altcoin (litecoin fork). Could you help us connect to ElectrumX database instead of Electrs?

Thanks

**Comment by herohero1232** [comment]
@cymich Talk to Litecoin Support on the [Litecointalk live support](https://live-litecoin.online/) so that your issue can be looked into.

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by cymich** [comment]
Thank you for answer,

Cant request 'block/height', I don't think this issue can be solved in the litecoin forum:

```
Task exception was never retrieved
future: <Task finished name='Task-4' coro=<update_block_list() done, defined at ../app/main.py:42> exception=ClientResponseError(RequestInfo(url=URL('http://127.0.0.1:3000/block/tip/height'), method='GET', headers=<CIMultiDictProxy('Host': '127.0.0.1:3000', 'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'Python/3.9 aiohttp/3.8.4')>, real_url=URL('http://127.0.0.1:3000/block/tip/height')), (), status=400, message='Expected HTTP/')>
Traceback (most recent call last):
  File "../venv/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 899, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "../venv/lib/python3.9/site-packages/aiohttp/streams.py", line 616, in read
    await self._waiter
  File "../venv/lib/python3.9/site-packages/aiohttp/client_proto.py", line 213, in data_received
    messages, upgraded, tail = self._parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadHttpMessage: 400, message='Expected HTTP/'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "../app/main.py", line 54, in update_block_list
    recent_blocks = await fetch.recent_blocks(BLOCKS_ON_INDEX)
  File "../app/fetch_blockchain_data.py", line 66, in recent_blocks
    current_height = await self.current_height()
  File "../app/fetch_blockchain_data.py", line 42, in current_height
    return int(await (await self._get(
  File "../app/fetch_blockchain_data.py", line 33, in _get
    return await self.session.get(
  File "../venv/lib/python3.9/site-packages/aiohttp/client.py", line 560, in _request
    await resp.start(conn)
  File "../venv/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 901, in start
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 400, message='Expected HTTP/', url=URL('http://127.0.0.1:3000/block/tip/height')
{'result': {}, 'error': None, 'id': 'curltext'}
```

**Comment by cymich** [comment]
I think I've figured it out ,the problem is in RESTAPI, electrumx is not able to provide the http path. Do you have any ideas how to simplify the query to this without writing a lot of code?

**Comment by herohero1232** [comment]
You could use a client-side library like axios to simplify the query. This library allows for easier configuration of HTTP requests and can even handle serialization and deserialization of request and response bodies. Additionally, the library can use the REST API directly, with no extra code needed.

**Comment by cymich** [comment]
Ok, thank you.

**Comment by moneroexamples** [comment]
The explorer is design for monero. Sadly I do not have time to modify it for other coins.
